# Generated by Django 5.1.6 on 2025-02-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('burger', 'Burger'), ('pizza', 'Pizza'), ('sandwiches', 'Sandwiches')], default='burger', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='product_images/')),
            ],
        ),
    ]
