# Generated by Django 5.1.6 on 2025-02-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('burger', 'Burger'), ('pizza', 'Pizza'), ('sandwiches', 'Sandwiches'), ('shawarmas', 'Shawarmas')], default='burger', max_length=50),
        ),
    ]
